#    ██████╗ ██╗██████╗  █████╗ ████████╗███████╗██████╗  █████╗ ██╗     ██╗
#    ██╔══██╗██║██╔══██╗██╔══██╗╚══██╔══╝██╔════╝██╔══██╗██╔══██╗██║     ██║
#    ██████╔╝██║██████╔╝███████║   ██║   █████╗  ██████╦╝███████║██║     ██║
#    ██╔═══╝ ██║██╔══██╗██╔══██║   ██║   ██╔══╝  ██╔══██╗██╔══██║██║     ██║
#    ██║     ██║██║  ██║██║  ██║   ██║   ███████╗██████╦╝██║  ██║███████╗███████╗
#    ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═════╝ ╚═╝  ╚═╝╚══════╝╚══════╝

required-players: 1

spectator-location: